In [10]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os
import json
import seaborn as sns



# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [7]:
weatherdata = pd.read_csv("../Output_data/DeltaTemp_GPMformat.csv")
weatherdata.head()

,City,Indicator,1951,1952,1953,1954,1955,1956,1957,1958,...,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
0,BOISE,Delta Temp (oC),0.0,2.61,3.03,2.43,1.86,1.88,2.67,3.68,...,2.78,2.92,3.30,2.84,4.40,2.47,3.76,4.43,3.90,3.07
1,BOSTON,Delta Temp (oC),0.0,0.18,0.94,-0.45,-0.47,-0.86,0.06,-2.33,...,-0.18,-0.78,0.87,0.61,1.08,-0.09,-0.61,-0.35,0.65,0.65
2,COLUMBUS,Delta Temp (oC),0.0,1.19,1.65,1.28,1.24,0.97,0.07,-0.46,...,1.06,0.76,1.23,1.67,2.83,1.18,0.43,0.99,1.98,2.28
3,DES MOINES,Delta Temp (oC),0.0,1.87,2.64,2.68,1.95,1.98,1.68,1.28,...,0.98,1.99,2.71,3.01,5.16,2.21,1.54,3.58,4.47,4.47
4,MIAMI,Delta Temp (oC),0.0,0.47,0.63,0.15,0.01,-0.03,0.38,-0.34,...,1.20,1.37,0.07,1.42,1.00,1.32,1.15,2.04,1.45,2.02

### Take mean of temp for all cities for the years 1951 and 2017

In [9]:
weather_data = weatherdata.loc[:, ["CITY", "1951", "2017"]]
weather_data = weather_data.groupby("CITY", as_index=False).mean()

weather_data

KeyError: 'Passing list-likes to .loc or [] with any missing labels is no longer supported, see https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#deprecate-loc-reindex-listlike'

In [4]:
lonlat = pd.read_csv("../Output_data/LatLon.csv")
#Rename column City to CITY
lonlat.rename(columns = {"City": "CITY"}, inplace = True)
#Change all the rows to upper case in column CITY
lonlat["CITY"] = lonlat["CITY"].str.upper()
lonlat = lonlat.loc[:, ["CITY", "Lat", "Lng"]]
lonlat.head()

         CITY    Lat    Lng
0      BOSTON  42.36 -71.06
1    COLUMBUS  39.96 -83.00
2       MIAMI  25.76 -80.19
3  DES MOINES  41.59 -93.63
4   NASHVILLE  36.17 -86.78

### Merge the two files

In [5]:
weather_data1 = pd.merge(weather_data, lonlat, on="CITY", how= "outer")

weather = weather_data1.dropna()
weather

              CITY    1951    2017    Lat     Lng
0            BOISE   8.550  11.600  43.62 -116.20
1           BOSTON  11.275   0.000  42.36  -71.06
2         COLUMBUS  10.775  13.075  39.96  -83.00
3       DES MOINES   8.200   0.000  41.59  -93.63
4            MIAMI  24.175  26.175  25.76  -80.19
5        NASHVILLE  15.125  16.925  36.17  -86.78
6      NEW ORLEANS   8.200   0.000  29.95  -90.07
7          PHOENIX  21.150  25.150  33.45 -112.07
8   SALT LAKE CITY  10.375  13.400  40.76 -111.89
9        SAN DIEGO  16.875  18.975  32.72 -117.16
10   SAN FRANCISCO  13.375  15.500  37.77 -122.42

### Temperature Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and 1951 as the weight.
* Add Heatmap layer to map.

In [6]:
# Configure gmaps
gmaps.configure(api_key=g_key)

# Use the Lat and Lng as locations and Humidity as the weight.
locations = weather[["Lat", "Lng"]]
meantemp_1951 = weather["1951"].astype(float)

# Plot Heatmap
fig = gmaps.figure(map_type="TERRAIN")

# Create heat layer
heat_layer = gmaps.heatmap_layer(locations, weights=meantemp_1951, 
                                 dissipating=False, max_intensity=weather["1951"].max(),
                                 point_radius=1)

# Add layer
fig.add_layer(heat_layer)

# Display figure
fig

Figure(layout=FigureLayout(height='420px'))

In [7]:
# Configure gmaps
gmaps.configure(api_key=g_key)

# Use the Lat and Lng as locations and Humidity as the weight.
locations = weather[["Lat", "Lng"]]
meantemp_2017 = weather["2017"].astype(float)

# Plot Heatmap
fig = gmaps.figure(map_type="TERRAIN")

# Create heat layer
heat_layer = gmaps.heatmap_layer(locations, weights=meantemp_2017, 
                                 dissipating=False, max_intensity=weather["2017"].max(),
                                 point_radius=1)

# Add layer
fig.add_layer(heat_layer)

# Display figure
fig

Figure(layout=FigureLayout(height='420px'))