## Statatistical Testing for PyWeatherman
### Suraj Thyagaraj
### 03/16/20

In [1]:
# Dependencies and Setup
import pandas as pd
import numpy as np
import scipy.stats as stats

# File to Load 
datafile = "WeatherData-monthly-filtered.xlsx"

# Read Purchasing File and store into Pandas data frame
# df = pd.read_csv(datafile)
df = pd.read_excel(datafile)

In [2]:
#Preliminary data analysis, checks
df.head(5)
list(df.columns)
df.describe()

,BOISE,BOSTON,COLUMBUS,DES MOINES,MIAMI,NASHVILLE,NEW ORLEANS,PHOENIX,SALT LAKE CITY,SAN DIEGO,SAN FRANCISCO,ST. PAUL
count,804.000000,804.000000,804.000000,804.000000,804.000000,804.000000,804.000000,804.000000,804.000000,804.000000,804.000000,804.000000
mean,10.954104,10.841045,11.439179,10.259826,24.702861,15.287313,20.548134,22.898881,11.436194,17.728856,14.194527,1.709453
std,8.732134,8.751099,9.288365,10.866093,3.433126,8.445765,6.168648,8.095303,9.522280,3.337050,3.114270,5.210810
min,-8.800000,-7.100000,-11.400000,-13.100000,0.000000,-4.200000,6.300000,0.000000,-7.000000,0.000000,0.000000,-13.100000
25%,3.475000,2.700000,3.000000,0.500000,22.100000,7.675000,15.100000,15.500000,3.175000,15.300000,11.700000,-2.225000
50%,10.400000,10.750000,12.250000,11.400000,25.300000,15.750000,20.900000,22.700000,11.100000,17.600000,14.400000,1.600000
75%,18.600000,19.100000,20.500000,20.400000,27.700000,23.525000,26.525000,30.825000,19.800000,20.400000,16.900000,6.425000
max,28.400000,25.600000,26.900000,29.100000,29.900000,30.500000,30.700000,36.900000,29.600000,26.100000,21.000000,16.000000

## Months Count

* Display the total number of months

In [3]:
# For total player count, count the total unique SN values
tp = df.nunique()['MONTH']
df_Months = pd.DataFrame([{"Total Months": df["MONTH"].nunique()}])
print(" There are " + str(tp) + " total months ")
df_Months

 There are 804 total months

   Total Months
0           804

In [4]:
# for column in df:
#     data = (df[column])
# data

## Monthly Statistics

* Create a list of elements corresponding to each month over the entire range of years + months


* Run One-sample t-test on the change in temperatures from initial value


* Display the summary results


* Loop over all months

In [5]:
months_df=['JANUARY','FEBRUARY','MARCH','APRIL','MAY','JUNE','JULY','AUGUST','SEPTEMBER','OCTOBER','NOVEMBER','DECEMBER']

for column in df.columns[1:]:
#     print(df[column])
#     print(df[column].name)
    print(f'{df[column].name} Monthly Statistics')
    print('------------------------')
    data_city = (df[column])
    
    imonth = 0 
    for month in months_df:
        data=data_city[imonth::12] 
        data = data.reset_index(drop=True)
        data = data-data[0]
        j = stats.ttest_1samp(data, 0) 
        p_val=j[1]/2
              
        if p_val < 0.05:
            if data.mean(axis = 0) > 0 :
                print("%s : Significant warming found ; Mean deltaT: % 2.1f, p-val: % 1.5f" %(month, data.mean(axis = 0)  , p_val)) 
            else :
                print("%s : Significant cooling found ; Mean deltaT: % 2.1f, p-val: % 1.5f" %(month, data.mean(axis = 0)  , p_val))
        else :
            print("%s : NO Significant warming/cooling found; Mean deltaT: % 2.1f, p-val: % 1.5f" %(month, data.mean(axis = 0), p_val))
        
        imonth = imonth + 1
    print('')

BOISE Monthly Statistics
------------------------
JANUARY : NO Significant warming/cooling found; Mean deltaT:  0.6, p-val:  0.05610
FEBRUARY : NO Significant warming/cooling found; Mean deltaT: -0.2, p-val:  0.21495
MARCH : Significant warming found ; Mean deltaT:  3.8, p-val:  0.00000
APRIL : Significant cooling found ; Mean deltaT: -0.6, p-val:  0.00311
MAY : Significant warming found ; Mean deltaT:  0.8, p-val:  0.00012
JUNE : Significant warming found ; Mean deltaT:  2.5, p-val:  0.00000
JULY : NO Significant warming/cooling found; Mean deltaT: -0.1, p-val:  0.35911
AUGUST : Significant warming found ; Mean deltaT:  0.8, p-val:  0.00038
SEPTEMBER : NO Significant warming/cooling found; Mean deltaT:  0.3, p-val:  0.13176
OCTOBER : Significant warming found ; Mean deltaT:  1.6, p-val:  0.00000
NOVEMBER : Significant warming found ; Mean deltaT:  0.6, p-val:  0.00742
DECEMBER : Significant warming found ; Mean deltaT:  2.2, p-val:  0.00000

BOSTON Monthly Statistics
------------------------
JANUARY : Significant cooling found ; Mean deltaT: -2.5, p-val:  0.00000
FEBRUARY : Significant cooling found ; Mean deltaT: -2.0, p-val:  0.00000
MARCH : Significant cooling found ; Mean deltaT: -0.4, p-val:  0.01537
APRIL : Significant cooling found ; Mean deltaT: -1.7, p-val:  0.00000
MAY : Significant cooling found ; Mean deltaT: -0.8, p-val:  0.01498
JUNE : Significant warming found ; Mean deltaT:  1.0, p-val:  0.00000
JULY : NO Significant warming/cooling found; Mean deltaT: -0.0, p-val:  0.46990
AUGUST : Significant warming found ; Mean deltaT:  0.9, p-val:  0.00000
SEPTEMBER : Significant cooling found ; Mean deltaT: -0.3, p-val:  0.01603
OCTOBER : NO Significant warming/cooling found; Mean deltaT: -0.1, p-val:  0.21249
NOVEMBER : Significant warming found ; Mean deltaT:  1.3, p-val:  0.00000
DECEMBER : NO Significant warming/cooling found; Mean deltaT: -0.3, p-val:  0.18106

COLUMBUS Monthly Statistics
------------------------
JANUARY : Significant warming found ; Mean deltaT:  1.2, p-val:  0.00081
FEBRUARY : NO Significant warming/cooling found; Mean deltaT:  0.2, p-val:  0.27135
MARCH : Significant warming found ; Mean deltaT:  0.6, p-val:  0.02395
APRIL : Significant warming found ; Mean deltaT:  1.2, p-val:  0.00000
MAY : Significant cooling found ; Mean deltaT: -0.5, p-val:  0.02775
JUNE : NO Significant warming/cooling found; Mean deltaT: -0.0, p-val:  0.47203
JULY : Significant warming found ; Mean deltaT:  0.3, p-val:  0.02432
AUGUST : Significant warming found ; Mean deltaT:  0.7, p-val:  0.00001
SEPTEMBER : Significant warming found ; Mean deltaT:  1.1, p-val:  0.00000
OCTOBER : Significant cooling found ; Mean deltaT: -1.4, p-val:  0.00000
NOVEMBER : Significant warming found ; Mean deltaT:  3.7, p-val:  0.00000
DECEMBER : Significant warming found ; Mean deltaT:  0.7, p-val:  0.01709

DES MOINES Monthly Statistics
------------------------
JANUARY : NO Significant warming/cooling found; Mean deltaT:  0.5, p-val:  0.11824
FEBRUARY : NO Significant warming/cooling found; Mean deltaT:  0.5, p-val:  0.11888
MARCH : Significant warming found ; Mean deltaT:  5.0, p-val:  0.00000
APRIL : Significant warming found ; Mean deltaT:  3.1, p-val:  0.00000
MAY : Significant cooling found ; Mean deltaT: -0.5, p-val:  0.01094
JUNE : Significant warming found ; Mean deltaT:  3.0, p-val:  0.00000
JULY : Significant warming found ; Mean deltaT:  1.6, p-val:  0.00000
AUGUST : Significant warming found ; Mean deltaT:  1.0, p-val:  0.00000
SEPTEMBER : Significant warming found ; Mean deltaT:  2.6, p-val:  0.00000
OCTOBER : Significant warming found ; Mean deltaT:  0.7, p-val:  0.00263
NOVEMBER : Significant warming found ; Mean deltaT:  3.9, p-val:  0.00000
DECEMBER : Significant warming found ; Mean deltaT:  3.3, p-val:  0.00000

MIAMI Monthly Statistics
------------------------
JANUARY : Significant warming found ; Mean deltaT:  1.3, p-val:  0.00000
FEBRUARY : Significant warming found ; Mean deltaT:  2.0, p-val:  0.00000
MARCH : Significant warming found ; Mean deltaT:  0.9, p-val:  0.00000
APRIL : Significant warming found ; Mean deltaT:  0.8, p-val:  0.02387
MAY : Significant warming found ; Mean deltaT:  0.8, p-val:  0.00000
JUNE : Significant warming found ; Mean deltaT:  0.3, p-val:  0.00015
JULY : Significant warming found ; Mean deltaT:  0.7, p-val:  0.00000
AUGUST : Significant cooling found ; Mean deltaT: -0.2, p-val:  0.01132
SEPTEMBER : Significant cooling found ; Mean deltaT: -0.3, p-val:  0.00002
OCTOBER : Significant warming found ; Mean deltaT:  0.5, p-val:  0.00000
NOVEMBER : Significant warming found ; Mean deltaT:  1.6, p-val:  0.00000
DECEMBER : Significant cooling found ; Mean deltaT: -1.8, p-val:  0.00000

NASHVILLE Monthly Statistics
------------------------
JANUARY : Significant cooling found ; Mean deltaT: -1.3, p-val:  0.00005
FEBRUARY : NO Significant warming/cooling found; Mean deltaT: -0.1, p-val:  0.34090
MARCH : NO Significant warming/cooling found; Mean deltaT:  0.2, p-val:  0.25009
APRIL : Significant warming found ; Mean deltaT:  2.4, p-val:  0.00000
MAY : NO Significant warming/cooling found; Mean deltaT:  0.2, p-val:  0.16602
JUNE : NO Significant warming/cooling found; Mean deltaT: -0.4, p-val:  0.13264
JULY : NO Significant warming/cooling found; Mean deltaT:  0.1, p-val:  0.29682
AUGUST : Significant cooling found ; Mean deltaT: -0.9, p-val:  0.00000
SEPTEMBER : NO Significant warming/cooling found; Mean deltaT: -0.0, p-val:  0.46834
OCTOBER : Significant cooling found ; Mean deltaT: -0.8, p-val:  0.00013
NOVEMBER : Significant warming found ; Mean deltaT:  3.9, p-val:  0.00000
DECEMBER : Significant cooling found ; Mean deltaT: -1.4, p-val:  0.00001

NEW ORLEANS Monthly Statistics
------------------------
JANUARY : Significant cooling found ; Mean deltaT: -2.4, p-val:  0.00000
FEBRUARY : Significant cooling found ; Mean deltaT: -1.0, p-val:  0.00025
MARCH : NO Significant warming/cooling found; Mean deltaT: -0.3, p-val:  0.10039
APRIL : Significant warming found ; Mean deltaT:  1.2, p-val:  0.00000
MAY : Significant warming found ; Mean deltaT:  0.5, p-val:  0.00045
JUNE : Significant cooling found ; Mean deltaT: -0.4, p-val:  0.00036
JULY : Significant cooling found ; Mean deltaT: -0.5, p-val:  0.00003
AUGUST : Significant cooling found ; Mean deltaT: -1.8, p-val:  0.00000
SEPTEMBER : Significant cooling found ; Mean deltaT: -0.7, p-val:  0.00002
OCTOBER : Significant cooling found ; Mean deltaT: -1.4, p-val:  0.00000
NOVEMBER : Significant warming found ; Mean deltaT:  2.5, p-val:  0.00000
DECEMBER : Significant cooling found ; Mean deltaT: -2.5, p-val:  0.00000

PHOENIX Monthly Statistics
------------------------
JANUARY : Significant warming found ; Mean deltaT:  1.4, p-val:  0.00000
FEBRUARY : Significant warming found ; Mean deltaT:  1.1, p-val:  0.00002
MARCH : Significant warming found ; Mean deltaT:  1.5, p-val:  0.00000
APRIL : Significant warming found ; Mean deltaT:  1.5, p-val:  0.00000
MAY : Significant warming found ; Mean deltaT:  1.6, p-val:  0.00000
JUNE : Significant warming found ; Mean deltaT:  3.3, p-val:  0.00000
JULY : Significant warming found ; Mean deltaT:  0.6, p-val:  0.00004
AUGUST : Significant warming found ; Mean deltaT:  2.6, p-val:  0.00000
SEPTEMBER : Significant warming found ; Mean deltaT:  1.9, p-val:  0.00000
OCTOBER : Significant warming found ; Mean deltaT:  1.8, p-val:  0.00000
NOVEMBER : Significant warming found ; Mean deltaT:  2.6, p-val:  0.00000
DECEMBER : Significant warming found ; Mean deltaT:  1.1, p-val:  0.00002

SALT LAKE CITY Monthly Statistics
------------------------
JANUARY : NO Significant warming/cooling found; Mean deltaT: -0.5, p-val:  0.08689
FEBRUARY : Significant cooling found ; Mean deltaT: -1.0, p-val:  0.00125
MARCH : Significant warming found ; Mean deltaT:  3.2, p-val:  0.00000
APRIL : NO Significant warming/cooling found; Mean deltaT: -0.1, p-val:  0.34945
MAY : NO Significant warming/cooling found; Mean deltaT:  0.2, p-val:  0.18122
JUNE : Significant warming found ; Mean deltaT:  0.9, p-val:  0.00015
JULY : Significant warming found ; Mean deltaT:  1.6, p-val:  0.00000
AUGUST : Significant warming found ; Mean deltaT:  1.6, p-val:  0.00000
SEPTEMBER : Significant warming found ; Mean deltaT:  0.9, p-val:  0.00004
OCTOBER : Significant warming found ; Mean deltaT:  1.5, p-val:  0.00000
NOVEMBER : Significant warming found ; Mean deltaT:  1.9, p-val:  0.00000
DECEMBER : Significant warming found ; Mean deltaT:  2.5, p-val:  0.00000

SAN DIEGO Monthly Statistics
------------------------
JANUARY : Significant warming found ; Mean deltaT:  0.9, p-val:  0.00000
FEBRUARY : Significant warming found ; Mean deltaT:  1.3, p-val:  0.00000
MARCH : Significant warming found ; Mean deltaT:  0.6, p-val:  0.00004
APRIL : NO Significant warming/cooling found; Mean deltaT:  0.2, p-val:  0.32393
MAY : Significant warming found ; Mean deltaT:  1.0, p-val:  0.00000
JUNE : Significant warming found ; Mean deltaT:  0.5, p-val:  0.00009
JULY : Significant warming found ; Mean deltaT:  0.6, p-val:  0.00001
AUGUST : Significant warming found ; Mean deltaT:  1.6, p-val:  0.00000
SEPTEMBER : Significant warming found ; Mean deltaT:  1.9, p-val:  0.00000
OCTOBER : Significant warming found ; Mean deltaT:  0.4, p-val:  0.00648
NOVEMBER : NO Significant warming/cooling found; Mean deltaT:  0.0, p-val:  0.46425
DECEMBER : Significant warming found ; Mean deltaT:  1.1, p-val:  0.00000

SAN FRANCISCO Monthly Statistics
------------------------
JANUARY : Significant cooling found ; Mean deltaT: -1.3, p-val:  0.00000
FEBRUARY : Significant cooling found ; Mean deltaT: -0.3, p-val:  0.01742
MARCH : Significant warming found ; Mean deltaT:  1.2, p-val:  0.00000
APRIL : Significant warming found ; Mean deltaT:  2.1, p-val:  0.00000
MAY : Significant warming found ; Mean deltaT:  0.3, p-val:  0.03532
JUNE : Significant warming found ; Mean deltaT:  1.4, p-val:  0.00000
JULY : Significant warming found ; Mean deltaT:  2.3, p-val:  0.00000
AUGUST : Significant warming found ; Mean deltaT:  1.0, p-val:  0.00044
SEPTEMBER : Significant warming found ; Mean deltaT:  1.2, p-val:  0.00000
OCTOBER : Significant warming found ; Mean deltaT:  0.6, p-val:  0.00002
NOVEMBER : Significant warming found ; Mean deltaT:  0.7, p-val:  0.00000
DECEMBER : Significant warming found ; Mean deltaT:  0.8, p-val:  0.00000

ST. PAUL Monthly Statistics
------------------------
JANUARY : Significant warming found ; Mean deltaT:  0.7, p-val:  0.01941
FEBRUARY : Significant cooling found ; Mean deltaT: -3.4, p-val:  0.00000
MARCH : NO Significant warming/cooling found; Mean deltaT:  0.2, p-val:  0.31660
APRIL : Significant warming found ; Mean deltaT:  1.2, p-val:  0.00000
MAY : Significant cooling found ; Mean deltaT: -1.8, p-val:  0.00000
JUNE : Significant cooling found ; Mean deltaT: -0.9, p-val:  0.00000
JULY : Significant warming found ; Mean deltaT:  1.6, p-val:  0.00000
AUGUST : NO Significant warming/cooling found; Mean deltaT: -0.1, p-val:  0.30653
SEPTEMBER : NO Significant warming/cooling found; Mean deltaT:  0.2, p-val:  0.12772
OCTOBER : Significant warming found ; Mean deltaT:  0.5, p-val:  0.00006
NOVEMBER : Significant cooling found ; Mean deltaT: -0.5, p-val:  0.00659
DECEMBER : Significant cooling found ; Mean deltaT: -1.5, p-val:  0.00000